<a href="https://colab.research.google.com/github/RushaliRajesh/DCEC/blob/main/Copy_of_DCEC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras.layers import Conv2D, Conv2DTranspose, Dense, Flatten, Reshape
from keras.models import Sequential, Model
from keras.utils.vis_utils import plot_model
import numpy as np
from sklearn.metrics import normalized_mutual_info_score, adjusted_rand_score

nmi = normalized_mutual_info_score
ari = adjusted_rand_score


def acc(y_true, y_pred):
    """
    Calculate clustering accuracy. Require scikit-learn installed
    # Arguments
        y: true labels, numpy.array with shape `(n_samples,)`
        y_pred: predicted labels, numpy.array with shape `(n_samples,)`
    # Return
        accuracy, in [0,1]
    """
    y_true = y_true.astype(np.int64)
    assert y_pred.size == y_true.size
    D = max(y_pred.max(), y_true.max()) + 1
    w = np.zeros((D, D), dtype=np.int64)
    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1
    !pip install scikit-learn==0.22.2
    from sklearn.utils.linear_assignment_ import linear_assignment
    ind = linear_assignment(w.max() - w)
    return float(sum([w[i, j] for i, j in ind])) * 1.0 / y_pred.size

def CAE(input_shape=(28, 28, 1), filters=[32, 64, 128, 10]):
    model = Sequential()
    if input_shape[0] % 8 == 0:
        pad3 = 'same'
    else:
        pad3 = 'valid'
    model.add(Conv2D(filters[0], 5, strides=2, padding='same', activation='relu', name='conv1', input_shape=input_shape))

    model.add(Conv2D(filters[1], 5, strides=2, padding='same', activation='relu', name='conv2'))

    model.add(Conv2D(filters[2], 3, strides=2, padding=pad3, activation='relu', name='conv3'))

    model.add(Flatten())
    model.add(Dense(units=filters[3], name='embedding'))
    model.add(Dense(units=filters[2]*int(input_shape[0]/8)*int(input_shape[0]/8), activation='relu'))

    model.add(Reshape((int(input_shape[0]/8), int(input_shape[0]/8), filters[2])))
    model.add(Conv2DTranspose(filters[1], 3, strides=2, padding=pad3, activation='relu', name='deconv3'))

    model.add(Conv2DTranspose(filters[0], 5, strides=2, padding='same', activation='relu', name='deconv2'))

    model.add(Conv2DTranspose(input_shape[2], 5, strides=2, padding='same', name='deconv1'))
    model.summary()
    return model

if __name__ == "__main__":
    from time import time

    # setting the hyper parameters
    import argparse

    class Args:
      dataset='mnist'
      n_clusters=10
      batch_size=256
      epochs=20
      save_dir='results/temp'
    args=Args()
    print(args)

    import os
    if not os.path.exists(args.save_dir):
        os.makedirs(args.save_dir)


    import numpy as np


    def load_mnist():
        # the data, shuffled and split between train and test sets
        from keras.datasets import mnist
        (x_train, y_train), (x_test, y_test) = mnist.load_data()

        x = np.concatenate((x_train, x_test))
        y = np.concatenate((y_train, y_test))
        x = x.reshape(-1, 28, 28, 1).astype('float32')
        x = x/255.
        print('MNIST:', x.shape)
        return x, y


    # # load dataset
    # from datasets import load_mnist, load_usps
    # if args.dataset == 'mnist':
    x, y = load_mnist()
    #print(x)
    # elif args.dataset == 'usps':
    #     x, y = load_usps('data/usps')

    # define the model
    model = CAE(input_shape=x.shape[1:], filters=[32, 64, 128, 10])
    plot_model(model, to_file=args.save_dir + '/%s-pretrain-model.png' % args.dataset, show_shapes=True)
    model.summary()

    # compile the model and callbacks
    optimizer = 'adam'
    model.compile(optimizer=optimizer, loss='mse')
    
    # begin training
    t0 = time()
    model.fit(x, x, batch_size=args.batch_size, epochs=args.epochs)
    print('Training time: ', time() - t0)
    #model.save(args.save_dir + '/%s-pretrain-model-%d.h5' % (args.dataset, args.epochs))

    # extract features
    feature_model = Model(inputs=model.input, outputs=model.get_layer(name='embedding').output)
    features = feature_model.predict(x)
    print('feature shape=', features.shape)

    # use features for clustering
    from sklearn.cluster import KMeans
    km = KMeans(n_clusters=args.n_clusters)

    features = np.reshape(features, newshape=(features.shape[0], -1))
    pred = km.fit_predict(features)

    from sklearn.metrics.cluster import normalized_mutual_info_score   
    from sklearn.metrics import accuracy_score 
    from sklearn.metrics.cluster import adjusted_rand_score
    #from . import metrics
    print('acc=', acc(y, pred), 'nmi=', nmi(y, pred), 'ari=', ari(y, pred))

11501568/11490434 [==============================] - 0s 0us/step
MNIST: (70000, 28, 28, 1)
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1 (Conv2D)              (None, 14, 14, 32)        832       
                                                                 
 conv2 (Conv2D)              (None, 7, 7, 64)          51264     
                                                                 
 conv3 (Conv2D)              (None, 3, 3, 128)         73856     
                                                                 
 flatten (Flatten)           (None, 1152)              0         
                                                                 
 embedding (Dense)           (None, 10)                11530     
                                                                 
 dense (Dense)               (None, 1152)              12672     
                               

acc= 0.8072285714285714 nmi= 0.7411959865499761 ari= 0.689977924408917


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


In [ ]:
def acc(y_true, y_pred):
    """
    Calculate clustering accuracy. Require scikit-learn installed
    # Arguments
        y: true labels, numpy.array with shape `(n_samples,)`
        y_pred: predicted labels, numpy.array with shape `(n_samples,)`
    # Return
        accuracy, in [0,1]
    """
    y_true = y_true.astype(np.int64)
    assert y_pred.size == y_true.size
    D = max(y_pred.max(), y_true.max()) + 1
    w = np.zeros((D, D), dtype=np.int64)
    print(w)
    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1
    print(w)
    !pip install scikit-learn==0.22.2
    from sklearn.utils.linear_assignment_ import linear_assignment
    ind = linear_assignment(w.max() - w)
    print(ind)
    return float(sum(([w[i, j] for i, j in ind])) * 1.0 / y_pred.size)
acc(y,pred)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[  35 7791   56   36   39   31  189   93   93   70]
 [6756    0  101   20    6   33   51   19   38   41]
 [   2    2   56   74    3    2    0 6670   12   57]
 [   0   56 6527   64    2    0    0   61    2    1]
 [   3    0    0   86    0 5628  220    0   52    6]
 [   0    8   16   25 3711   17    6  187   43 2527]
 [  41    1   26   10   24  154 6354    0   34    1]
 [  30   12   18    7 3037   20    5  235   85 4096]
 [  34    7  102  184    2  112   50   26 6375  100]
 [   2    0   88 6635    0  316    1    2   91   59]]
[[0 1]
 [1 0]
 [2 7]
 [3 2]
 [4 5]
 [5 4]
 [6 6]
 [7 9]
 [8 8]
 [9 3]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


0.8649

In [ ]:
from scipy.optimize import linear_sum_assignment as linear_assignment

In [ ]:
pip install .

ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.


In [2]:
from time import time
import numpy as np
import keras.backend as K
from tensorflow.keras.layers import Layer, InputSpec
from keras.models import Model
from keras.utils.vis_utils import plot_model
from sklearn.cluster import KMeans
from keras.models import Sequential
from keras.layers import Conv2D, Conv2DTranspose, Dense, Flatten, Reshape

#from ConvAE import CAE


class ClusteringLayer(Layer):
    """
    Clustering layer converts input sample (feature) to soft label, i.e. a vector that represents the probability of the
    sample belonging to each cluster. The probability is calculated with student's t-distribution.
    # Example
    ```
        model.add(ClusteringLayer(n_clusters=10))
    ```
    # Arguments
        n_clusters: number of clusters.
        weights: list of Numpy array with shape `(n_clusters, n_features)` witch represents the initial cluster centers.
        alpha: parameter in Student's t-distribution. Default to 1.0.
    # Input shape
        2D tensor with shape: `(n_samples, n_features)`.
    # Output shape
        2D tensor with shape: `(n_samples, n_clusters)`.
    """

    def __init__(self, n_clusters, weights=None, alpha=1.0, **kwargs):
        if 'input_shape' not in kwargs and 'input_dim' in kwargs:
            kwargs['input_shape'] = (kwargs.pop('input_dim'),)
        super(ClusteringLayer, self).__init__(**kwargs)
        self.n_clusters = n_clusters
        self.alpha = alpha
        self.initial_weights = weights
        self.input_spec = InputSpec(ndim=2)

    def build(self, input_shape):
        assert len(input_shape) == 2
        input_dim = input_shape[1]
        self.input_spec = InputSpec(dtype=K.floatx(), shape=(None, input_dim))
        self.clusters = self.add_weight(shape=(self.n_clusters, input_dim), initializer='glorot_uniform', name='clusters')
        if self.initial_weights is not None:
            self.set_weights(self.initial_weights)
            del self.initial_weights
        self.built = True

    def call(self, inputs, **kwargs):
        """ student t-distribution, as same as used in t-SNE algorithm.
                 q_ij = 1/(1+dist(x_i, u_j)^2), then normalize it.
        Arguments:
            inputs: the variable containing data, shape=(n_samples, n_features)
        Return:
            q: student's t-distribution, or soft labels for each sample. shape=(n_samples, n_clusters)
        """
        q = 1.0 / (1.0 + (K.sum(K.square(K.expand_dims(inputs, axis=1) - self.clusters), axis=2) / self.alpha))
        q **= (self.alpha + 1.0) / 2.0
        q = K.transpose(K.transpose(q) / K.sum(q, axis=1))
        return q

    def compute_output_shape(self, input_shape):
        assert input_shape and len(input_shape) == 2
        return input_shape[0], self.n_clusters

    def get_config(self):
        config = {'n_clusters': self.n_clusters}
        base_config = super(ClusteringLayer, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))


class DCEC(object):
    def __init__(self,
                 input_shape,
                 filters=[32, 64, 128, 10],
                 n_clusters=10,
                 alpha=1.0):

        super(DCEC, self).__init__()

        self.n_clusters = n_clusters
        self.input_shape = input_shape
        self.alpha = alpha
        self.pretrained = False
        self.y_pred = []

        self.cae = CAE(input_shape, filters)
        hidden = self.cae.get_layer(name='embedding').output
        self.encoder = Model(inputs=self.cae.input, outputs=hidden)

        # Define DCEC model
        clustering_layer = ClusteringLayer(self.n_clusters, name='clustering')(hidden)
        self.model = Model(inputs=self.cae.input,
                           outputs=[clustering_layer, self.cae.output])

    def pretrain(self, x, batch_size=256, epochs=20, optimizer='adam', save_dir='results/temp'):
        print('...Pretraining...')
        self.cae.compile(optimizer=optimizer, loss='mse')
        #from keras.callbacks import CSVLogger
        #csv_logger = CSVLogger(args.save_dir + '/pretrain_log.csv')

        # begin training
        t0 = time()
        self.cae.fit(x, x, batch_size=batch_size, epochs=epochs)
        print('Pretraining time: ', time() - t0)
        self.cae.save(save_dir + '/pretrain_cae_model.h5')
        print('Pretrained weights are saved to %s/pretrain_cae_model.h5' % save_dir)
        self.pretrained = True

    def load_weights(self, weights_path):
        self.model.load_weights(weights_path)

    def extract_feature(self, x):  # extract features from before clustering layer
        return self.encoder.predict(x)

    def predict(self, x):
        q, _ = self.model.predict(x, verbose=0)
        return q.argmax(1)

    @staticmethod
    def target_distribution(q):
        weight = q ** 2 / q.sum(0)
        return (weight.T / weight.sum(1)).T

    def compile(self, loss=['kld', 'mse'], loss_weights=[1, 1], optimizer='adam'):
        self.model.compile(loss=loss, loss_weights=loss_weights, optimizer=optimizer)

    def fit(self, x, y=None, batch_size=256, maxiter=2e4, tol=1e-3,
            update_interval=140, cae_weights=None, save_dir='./results/temp'):

        print('Update interval', update_interval)
        save_interval = x.shape[0] / batch_size * 5
        print('Save interval', save_interval)

        # Step 1: pretrain if necessary
        t0 = time()
        if not self.pretrained and cae_weights is None:
            print('...pretraining CAE using default hyper-parameters:')
            print('   optimizer=\'adam\';   epochs=200')
            self.pretrain(x, batch_size, save_dir=save_dir)
            self.pretrained = True
        elif cae_weights is not None:
            self.cae.load_weights(cae_weights)
            print('cae_weights is loaded successfully.')

        # Step 2: initialize cluster centers using k-means
        t1 = time()
        print('Initializing cluster centers with k-means.')
        kmeans = KMeans(n_clusters=self.n_clusters, n_init=20)
        self.y_pred = kmeans.fit_predict(self.encoder.predict(x))
        y_pred_last = np.copy(self.y_pred)
        self.model.get_layer(name='clustering').set_weights([kmeans.cluster_centers_])

        # Step 3: deep clustering
        # logging file
        import csv, os
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        logfile = open(save_dir + '/dcec_log.csv', 'w')
        logwriter = csv.DictWriter(logfile, fieldnames=['iter', 'acc', 'nmi', 'ari', 'L', 'Lc', 'Lr'])
        logwriter.writeheader()

        t2 = time()
        loss = [0, 0, 0]
        index = 0
        for ite in range(int(maxiter)):
            if ite % update_interval == 0:
                q, _ = self.model.predict(x, verbose=0)
                p = self.target_distribution(q)  # update the auxiliary target distribution p

                # evaluate the clustering performance
                self.y_pred = q.argmax(1)
                if y is not None:
                    acc1 = np.round(acc(y, self.y_pred), 5)
                    nmi1 = np.round(nmi(y, self.y_pred), 5)
                    ari1 = np.round(ari(y, self.y_pred), 5)
                    loss = np.round(loss, 5)
                    logdict = dict(iter=ite, acc=acc1, nmi=nmi1, ari=ari1, L=loss[0], Lc=loss[1], Lr=loss[2])
                    logwriter.writerow(logdict)
                    print('Iter', ite, ': Acc', acc, ', nmi', nmi, ', ari', ari, '; loss=', loss)

                # check stop criterion
                delta_label = np.sum(self.y_pred != y_pred_last).astype(np.float32) / self.y_pred.shape[0]
                y_pred_last = np.copy(self.y_pred)
                if ite > 0 and delta_label < tol:
                    print('delta_label ', delta_label, '< tol ', tol)
                    print('Reached tolerance threshold. Stopping training.')
                    logfile.close()
                    break

            # train on batch
            if (index + 1) * batch_size > x.shape[0]:
                loss = self.model.train_on_batch(x=x[index * batch_size::],
                                                 y=[p[index * batch_size::], x[index * batch_size::]])
                index = 0
            else:
                loss = self.model.train_on_batch(x=x[index * batch_size:(index + 1) * batch_size],
                                                 y=[p[index * batch_size:(index + 1) * batch_size],
                                                    x[index * batch_size:(index + 1) * batch_size]])
                index += 1

            # save intermediate model
            if ite % save_interval == 0:
                # save DCEC model checkpoints
                print('saving model to:', save_dir + '/dcec_model_' + str(ite) + '.h5')
                self.model.save_weights(save_dir + '/dcec_model_' + str(ite) + '.h5')

            ite += 1
        # save the trained model
        logfile.close()
        print('saving model to:', save_dir + '/dcec_model_final.h5')
        self.model.save_weights(save_dir + '/dcec_model_final.h5')
        t3 = time()
        print('Pretrain time:  ', t1 - t0)
        print('Clustering time:', t3 - t1)
        print('Total time:     ', t3 - t0)


if __name__ == "__main__":
    # setting the hyper parameters
    import argparse
    class Args:
      dataset='mnist'
      n_clusters=10
      batch_size=256
      maxiter=2e4
      gamma=0.1
      update_interval=140
      tol=0.001
      cae_weights=None
      save_dir='results/temp'
    
    args = Args()
    print(args)

    import os
    if not os.path.exists(args.save_dir):
        os.makedirs(args.save_dir)

    # load dataset
    #from datasets import load_mnist, load_usps
    if args.dataset == 'mnist':
        x, y = load_mnist()
    # elif args.dataset == 'usps':
    #     x, y = load_usps('data/usps')
    # elif args.dataset == 'mnist-test':
    #     x, y = load_mnist()
        x, y = x[60000:], y[60000:]

    # prepare the DCEC model
    dcec = DCEC(input_shape=x.shape[1:], filters=[32, 64, 128, 10], n_clusters=args.n_clusters)
    plot_model(dcec.model, to_file=args.save_dir + '/dcec_model.png', show_shapes=True)
    dcec.model.summary()

    # begin clustering.
    optimizer = 'adam'
    dcec.compile(loss=['kld', 'mse'], loss_weights=[args.gamma, 1], optimizer=optimizer)
    dcec.fit(x, y=y, tol=args.tol, maxiter=args.maxiter,
             update_interval=args.update_interval,
             save_dir=args.save_dir,
             cae_weights=args.cae_weights)
    y_pred = dcec.y_pred
    print('acc = %.4f, nmi = %.4f, ari = %.4f' % (acc(y, y_pred), nmi(y, y_pred), ari(y, y_pred)))

MNIST: (70000, 28, 28, 1)
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1 (Conv2D)              (None, 14, 14, 32)        832       
                                                                 
 conv2 (Conv2D)              (None, 7, 7, 64)          51264     
                                                                 
 conv3 (Conv2D)              (None, 3, 3, 128)         73856     
                                                                 
 flatten_1 (Flatten)         (None, 1152)              0         
                                                                 
 embedding (Dense)           (None, 10)                11530     
                                                                 
 dense_1 (Dense)             (None, 1152)              12672     
                                                                 
 reshape_1 (Reshape)        

/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 0 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0 0 0]
saving model to: results/temp/dcec_model_0.h5


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 140 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02057 0.05511 0.01506]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 280 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02142 0.07464 0.01396]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 420 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.0346  0.15147 0.01945]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 560 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02519 0.11616 0.01357]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 700 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.03663 0.16076 0.02055]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 840 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02228 0.09297 0.01298]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 980 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.03368 0.14637 0.01904]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1120 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02096 0.08233 0.01272]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1260 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.03331 0.1352  0.01979]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1400 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02385 0.07953 0.0159 ]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1540 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.03181 0.12502 0.01931]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1680 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01903 0.07251 0.01178]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1820 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02841 0.11041 0.01737]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 1960 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01861 0.07385 0.01122]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2100 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02974 0.11098 0.01865]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2240 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02037 0.07    0.01337]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2380 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02761 0.10836 0.01678]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2520 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.0164  0.05786 0.01061]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2660 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02835 0.10347 0.018  ]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2800 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01576 0.0572  0.01004]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 2940 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02701 0.09625 0.01738]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3080 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01644 0.05871 0.01057]
saving model to: results/temp/dcec_model_3125.h5


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3220 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02673 0.09956 0.01677]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3360 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.0153  0.06884 0.00841]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3500 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02452 0.08902 0.01561]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3640 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01784 0.06513 0.01132]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3780 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02585 0.08748 0.0171 ]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 3920 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01498 0.05523 0.00946]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 4060 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02395 0.07997 0.01595]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 4200 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01628 0.06885 0.00939]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 4340 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.02287 0.07712 0.01515]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


Iter 4480 : Acc <function acc at 0x7fb7970730e0> , nmi <function normalized_mutual_info_score at 0x7fb7214abd40> , ari <function adjusted_rand_score at 0x7fb7214ab950> ; loss= [0.01302 0.04382 0.00864]
delta_label  0.0008 < tol  0.001
Reached tolerance threshold. Stopping training.
saving model to: results/temp/dcec_model_final.h5
Pretrain time:   239.14146614074707
Clustering time: 1582.9631507396698
Total time:      1822.1046168804169
acc = 0.7893, nmi = 0.7596, ari = 0.6894


/usr/local/lib/python3.7/dist-packages/sklearn/utils/linear_assignment_.py:128: FutureWarning: The linear_assignment function is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)


In [ ]:
from sklearn.metrics.cluster import normalized_mutual_info_score   
from sklearn.metrics import accuracy_score 
from sklearn.metrics.cluster import adjusted_rand_score
def load_mnist():
        # the data, shuffled and split between train and test sets
        from keras.datasets import mnist
        (x_train, y_train), (x_test, y_test) = mnist.load_data()

        x = np.concatenate((x_train, x_test))
        y = np.concatenate((y_train, y_test))
        x = x.reshape(-1, 28, 28, 1).astype('float32')
        x = x/255.
        print('MNIST:', x.shape)
        return x, y

In [4]:
y_pred.shape,y.shape

((10000,), (10000,))

In [ ]:
def CAE(input_shape=(28, 28, 1), filters=[32, 64, 128, 10]):
    model = Sequential()
    if input_shape[0] % 8 == 0:
        pad3 = 'same'
    else:
        pad3 = 'valid'
    model.add(Conv2D(filters[0], 5, strides=2, padding='same', activation='relu', name='conv1', input_shape=input_shape))

    model.add(Conv2D(filters[1], 5, strides=2, padding='same', activation='relu', name='conv2'))

    model.add(Conv2D(filters[2], 3, strides=2, padding=pad3, activation='relu', name='conv3'))

    model.add(Flatten())
    model.add(Dense(units=filters[3], name='embedding'))
    model.add(Dense(units=filters[2]*int(input_shape[0]/8)*int(input_shape[0]/8), activation='relu'))

    model.add(Reshape((int(input_shape[0]/8), int(input_shape[0]/8), filters[2])))
    model.add(Conv2DTranspose(filters[1], 3, strides=2, padding=pad3, activation='relu', name='deconv3'))

    model.add(Conv2DTranspose(filters[0], 5, strides=2, padding='same', activation='relu', name='deconv2'))

    model.add(Conv2DTranspose(input_shape[2], 5, strides=2, padding='same', name='deconv1'))
    model.summary()
    return model